[2025-05-18T07:53:27.001+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: flight_price_pipeline.ingest_data manual__2025-05-18T07:48:24.544432+00:00 [queued]>
[2025-05-18T07:53:27.012+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: flight_price_pipeline.ingest_data manual__2025-05-18T07:48:24.544432+00:00 [queued]>
[2025-05-18T07:53:27.013+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2025-05-18T07:53:27.030+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): ingest_data> on 2025-05-18 07:48:24.544432+00:00
[2025-05-18T07:53:27.035+0000] {standard_task_runner.py:60} INFO - Started process 480 to run task
[2025-05-18T07:53:27.039+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'flight_price_pipeline', 'ingest_data', 'manual__2025-05-18T07:48:24.544432+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/flight_price_.py', '--cfg-path', '/tmp/tmpu4tn6wa0']
[2025-05-18T07:53:27.042+0000] {standard_task_runner.py:88} INFO - Job 8: Subtask ingest_data
[2025-05-18T07:53:27.101+0000] {task_command.py:423} INFO - Running <TaskInstance: flight_price_pipeline.ingest_data manual__2025-05-18T07:48:24.544432+00:00 [running]> on host d05befceb79d
[2025-05-18T07:53:27.206+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='flight_price_pipeline' AIRFLOW_CTX_TASK_ID='ingest_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-18T07:48:24.544432+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-18T07:48:24.544432+00:00'
[2025-05-18T07:53:27.212+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/flight_price_.py", line 8, in ingest_data
    from scripts.data_ingestion import ingest_data
ModuleNotFoundError: No module named 'scripts.data_ingestion'
[2025-05-18T07:53:27.238+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=flight_price_pipeline, task_id=ingest_data, execution_date=20250518T074824, start_date=20250518T075327, end_date=20250518T075327
[2025-05-18T07:53:27.262+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 8 for task ingest_data (No module named 'scripts.data_ingestion'; 480)
[2025-05-18T07:53:27.293+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-05-18T07:53:27.313+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
