[2025-05-18T07:54:08.043+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: flight_price_pipeline.ingest_data manual__2025-05-18T07:49:05.693999+00:00 [queued]>
[2025-05-18T07:54:08.054+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: flight_price_pipeline.ingest_data manual__2025-05-18T07:49:05.693999+00:00 [queued]>
[2025-05-18T07:54:08.055+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2025-05-18T07:54:08.073+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): ingest_data> on 2025-05-18 07:49:05.693999+00:00
[2025-05-18T07:54:08.078+0000] {standard_task_runner.py:60} INFO - Started process 487 to run task
[2025-05-18T07:54:08.082+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'flight_price_pipeline', 'ingest_data', 'manual__2025-05-18T07:49:05.693999+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/flight_price_.py', '--cfg-path', '/tmp/tmp_2yd8q14']
[2025-05-18T07:54:08.085+0000] {standard_task_runner.py:88} INFO - Job 9: Subtask ingest_data
[2025-05-18T07:54:08.152+0000] {task_command.py:423} INFO - Running <TaskInstance: flight_price_pipeline.ingest_data manual__2025-05-18T07:49:05.693999+00:00 [running]> on host d05befceb79d
[2025-05-18T07:54:08.271+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='flight_price_pipeline' AIRFLOW_CTX_TASK_ID='ingest_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-18T07:49:05.693999+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-18T07:49:05.693999+00:00'
[2025-05-18T07:54:08.278+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/flight_price_.py", line 8, in ingest_data
    from scripts.data_ingestion import ingest_data
ModuleNotFoundError: No module named 'scripts.data_ingestion'
[2025-05-18T07:54:08.305+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=flight_price_pipeline, task_id=ingest_data, execution_date=20250518T074905, start_date=20250518T075408, end_date=20250518T075408
[2025-05-18T07:54:08.321+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 9 for task ingest_data (No module named 'scripts.data_ingestion'; 487)
[2025-05-18T07:54:08.336+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-05-18T07:54:08.358+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
